In [61]:
sentences  = [ "Three years later the coffin was full of jello", 
                "There is not time to fill the coffin of jello",
               ]



model_name = 'bert-base-nli-mean-tokens'

In [62]:
from sentence_transformers import SentenceTransformer


In [63]:
model =  SentenceTransformer(model_name)

In [64]:
sentence_vectors = model.encode(sentences)

In [65]:
sentence_vectors
type(sentence_vectors)

numpy.ndarray

In [66]:
sentence_vectors.shape

(2, 768)

In [67]:
from sklearn.metrics.pairwise import cosine_similarity

In [68]:
cosine_similarity(
    [sentence_vectors[0]],sentence_vectors[1:]
)




array([[0.5735097]], dtype=float32)

In [75]:
sentence_vectors
type(sentence_vectors)


numpy.ndarray

In [87]:
a = (sentence_vectors[0])
b = sentence_vectors[1]


a.ndim

1

## Difference Between Arrays 

In [90]:

a-b 


array([-3.56171668e-01, -7.18489170e-01, -1.08557177e+00, -5.05117476e-01,
       -2.98727807e-02, -7.01191425e-01, -1.31330860e+00,  3.86212826e-01,
       -6.07984781e-01,  3.26896936e-01,  7.27109313e-01, -3.01190078e-01,
        4.46431637e-02, -1.94023728e-01, -2.87893862e-01,  2.60072500e-02,
       -6.46616876e-01,  4.75183159e-01,  5.08295953e-01, -2.48794496e-01,
        2.67797172e-01,  2.31641531e-02, -4.09567297e-01, -2.31417298e-01,
       -1.54651165e-01,  6.43337131e-01,  8.36576700e-01, -5.24373174e-01,
        9.27305222e-02, -2.34248728e-01, -3.10990453e-01,  1.34193465e-01,
       -2.60794818e-01,  4.55527306e-01, -1.16423714e+00, -9.41239893e-02,
       -5.81038594e-01,  2.12777555e-01, -2.78447717e-01,  1.01005256e+00,
        4.54666167e-01, -3.65853012e-01,  3.51095289e-01, -9.69526470e-02,
       -6.33364737e-01, -4.86982048e-01, -9.05038655e-01,  6.38033152e-01,
       -2.23774523e-01,  3.11187059e-01,  1.38875902e-01, -1.34814546e-01,
       -1.34055340e+00, -

## Comparison 

In [91]:
a > b 
a < b 

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True, False,  True,  True, False,  True, False,
       False,  True, False, False,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False, False,  True, False,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True, False, False,  True,  True,
       False, False, False,  True, False,  True, False,  True,  True,
       False,  True, False, False,  True, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True, False,
       False,  True, False, False, False,  True, False,  True, False,
        True,  True, False,  True, False,  True, False,  True,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False,

## Similarity
I am using cosine similiarty since we have a 1 dimentional array. 

In [94]:
print("Dimention Of Array: " , a.ndim  , " ", b.ndim)

Dimention Of Array:  1   1


In [95]:
from numpy import dot
from numpy.linalg import norm


In [97]:
cos_sim = dot(a, b)/(norm(a)*norm(b))

print(cos_sim)


0.57350963
